TodoList/Models/Task.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace TodoList.Models
{
    public class Task
    {
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Comments { get; set; }

        public bool Completed { get; set; }
    }
}

TodoList/Models/TodoListDbContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace TodoList.Models
{
    public class TodoListDbContext : DbContext
    {
        public virtual IDbSet<Task> Tasks { get; set; }

        public TodoListDbContext() : base("TodoListDb")
        {
        }
    }
}

TodoList/Controllers/TaskController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using TodoList.Models;

namespace TodoList.Controllers
{
	public class TaskController : Controller
	{
	    [HttpGet]
        [Route("")]
	    public ActionResult Index()
	    {
            using (var db = new TodoListDbContext())
            {
                var tasks = db.Tasks.ToList();
                return View(tasks);
            }
        }

        [HttpGet]
        [Route("create")]
        public ActionResult Create()
		{
            return View();
        }

		[HttpPost]
		[Route("create")]
        [ValidateAntiForgeryToken]
		public ActionResult Create(Task task)
		{
            if (ModelState.IsValid)
            {
                using (var db = new TodoListDbContext())
                {
                    db.Tasks.Add(task);
                    db.SaveChanges();
                    return Redirect("/");
                }
            }
            return View();
        }

		[HttpGet]
		[Route("delete/{id}")]
        public ActionResult Delete(int? id)
		{
            using (var db = new TodoListDbContext())
            {
                var task = db.Tasks.Find(id);
                if (task != null)
                {
                    return View(task);
                }
            }
            return Redirect("/");
        }

		[HttpPost]
		[Route("delete/{id}")]
        [ValidateAntiForgeryToken]
		public ActionResult DeleteConfirm(int id)
		{
            using (var db = new TodoListDbContext())
            {
                var task = db.Tasks.Find(id);
                if (task != null)
                {
                    db.Tasks.Remove(task);
                    db.SaveChanges();
                }
            }
            return Redirect("/");
        }

        [HttpGet]
        [Route("edit/{id}")]
        public ActionResult Edit(int? id)
        {
            using (var db = new TodoListDbContext())
            {
                var task = db.Tasks.Find(id);
                if (task != null)
                {
                    return View(task);
                }
            }
            return Redirect("/");
        }

        [HttpPost]
        [Route("edit/{id}")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Task task)
        {
            if (!ModelState.IsValid)
            {
                return View(task);
            }

            using (var db = new TodoListDbContext())
            {
                var taskFromDb = db.Tasks.Find(task.Id);
                if (taskFromDb != null)
                {
                    taskFromDb.Title = task.Title;
                    taskFromDb.Comments = task.Comments;
                    db.SaveChanges();
                }
            }
            return Redirect("/");
        }
    }
}

TodoList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ToDo List</title>
    @Styles.Render("~/Content/index-style.css");
    @Styles.Render("~/Content/create-style.css");
    @Styles.Render("~/Content/delete-style.css");
</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>
</body>
</html>

TodoList/Views/Task/Create.cshtml
@model TodoList.Models.Task

@{
    ViewBag.Title = "Create";
}

<div id="create-wrapper">
    <section class="create">
        <article>
            @using (Html.BeginForm("Create", "Task", FormMethod.Post))
            {
                <div class="row">
                    <label for="task">Task:</label>
                    @Html.TextBoxFor(m => m.Title, new {@id = "task"})
                </div>
                <div class="row">
                    <label for="comments">Comments:</label>
                    @Html.TextAreaFor(m => m.Comments, new { @id = "comments" })
                </div>
	            <button type="submit">Create</button>

	            @Html.AntiForgeryToken()
            }
        </article>
    </section>
</div>

TodoList/Views/Task/Delete.cshtml
@model TodoList.Models.Task

@{
	ViewBag.Title = "Delete";
}

<div id="delete-wrapper">
	<section class="delete">
		<article>
			@using (Html.BeginForm("DeleteConfirm", "Task", new {id = Model.Id}, FormMethod.Post, null))
			{
				<h4>Do you want to delete this item?</h4>
				<div class="box">
					<p>@Model.Title</p>
				</div>
				<div class="box">
					<p class="description">@Model.Comments</p>
				</div>
				<button type="submit">Delete</button>
				<a href="/">Cancel</a>

				@Html.AntiForgeryToken()
			}
		</article>
	</section>
</div>

TodoList/Views/Task/Edit.cshtml
@model TodoList.Models.Task

@{
    ViewBag.Title = "Edit";
}

<div id="create-wrapper">
    <section class="create">
        <article>
            @using (Html.BeginForm("Edit", "Task", FormMethod.Post))
            {
                <div class="row">
                    <label for="task">Task:</label>
                    @Html.TextBoxFor(m => m.Title, new {@id = "task"})
                </div>
                <div class="row">
                    <label for="comments">Comments:</label>
                    @Html.TextAreaFor(m => m.Comments, new { @id = "comments" })
                </div>
	            <button type="submit">Edit</button>

	            @Html.AntiForgeryToken()
            }
        </article>
    </section>
</div>

TodoList/Views/Task/Index.cshtml
@model List<TodoList.Models.Task> 

@{
    ViewBag.Title = "Index";
}

<section class="home">
    <h1>VTS</h1>
    <h2>Tasks:</h2>
    @foreach (var task in Model)
    {
        <article>
            @Html.ActionLink("X", "Delete", "Task", new { id = task.Id }, new {@class="fa fa-window-close"})
            <h3>@task.Title</h3>
            <p>@task.Comments</p>
        </article>
    }
    @Html.ActionLink("Create New", "Create", "Task", null, new {@id="create-button"} )
</section>